markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Katy Huff
url: http://katyhuff.github.com/left
description: ipsa dixit
twitter: katyhuff
github: katyhuff
gravatar_url: http://www.gravatar.com/avatar/95edf87e1bee6782e38f18d6813cc74e

comments: true
